#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/application
- name: Restart application container
  ansible.builtin.docker_container:
    name: application
    state: restarted
  become: true