#SPDX-License-Identifier: MIT-0
---
- name: Update APT cache
  ansible.builtin.apt:
    update-cache: true
    upgrade: dist

- name: Ensure common utils are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - wget
    - unzip
    - vim
    - tmux
    - git
    - python3
    - python3-pip
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg