pipeline{
    agent any
    
    
    environment {
        DEPLOYMENT_ENV = 'testing'
        MAINTAINER = "david"
    }
    
    stages{
        stage('Checkout'){
            steps{
                sh "sleep 2" 
                echo "code checked out from repo successfully"
            }
        }
        
        stage('Build'){
            steps{
                echo 'Build completed'
            }
        }
        
        stage('Deploy'){
            steps{
                sh "sleep 3"
                echo 'Build completed'
            }
        }
    }
}
