#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/web
- name: Install docker
  ansible.builtin.apt:
    name: docker.io={{ docker_version }}
    state: present
    update_cache: true
  become: true

- name: Install Nginx
  ansible.builtin.docker_container:
    name: nginx
    image: "nginx:{{ nginx_version }}"
    ports: 
      "80:80"
    volumes:
      "etc/nginx/nginx.conf:etc/nginx/nginx.conf"
    state: started
    restart_policy: always
  become: true
  notify: Restart Nginx
